// Mock response generators for the P&L assistant

export type FollowUpAction =
  | { type: "chat"; label: string; intent: string }
  | { type: "report"; label: string; report_type: string; params?: Record<string, unknown> };

export interface MockResponse {
  content: string;
  showArtifact?: boolean;
  followUpQuestions?: FollowUpAction[];
}

export const generateReportContent = (query: string): string => {
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  let category = "General Analysis";
  let executiveSummary = "Based on the current period's data, we observed significant variance in line with your query. This report breaks down the key drivers, historical trends, and recommended actions.";
  let recommendations = `
1. **Immediate**: Review vendor contracts for top 3 ingredients.
2. **Short-term**: Adjust staffing levels for Tuesday/Wednesday shifts.
3. **Strategic**: Consider a limited-time offer to boost weekday traffic.
`;

  if (query.toLowerCase().includes('labor') || query.toLowerCase().includes('staff')) {
    category = "Labor Analysis";
    executiveSummary = "Labor costs are currently tracking 1.5% above budget, primarily driven by overtime in BOH and holiday staffing. Efficiency metrics (Sales Per Labor Hour) have dipped slightly.";
    recommendations = `
1. **Immediate**: Implement strict overtime approval process for BOH.
2. **Short-term**: Audit schedule vs. actuals for the last 4 weeks to identify recurring overages.
3. **Strategic**: Cross-train prep cooks to optimize mid-shift coverage.
`;
  } else if (query.toLowerCase().includes('food') || query.toLowerCase().includes('cogs') || query.toLowerCase().includes('cost')) {
    category = "COGS Analysis";
    executiveSummary = "Food costs have stabilized but remain 0.8% above target. Protein costs (specifically beef and seafood) are the primary drivers of this variance.";
    recommendations = `
1. **Immediate**: Conduct a spot inventory of high-value proteins.
2. **Short-term**: Renegotiate pricing with primary protein vendor or explore alternative cuts.
3. **Strategic**: Review portion control protocols and waste logs.
`;
  } else if (query.toLowerCase().includes('sales') || query.toLowerCase().includes('revenue')) {
     category = "Revenue Analysis";
     executiveSummary = "Revenue is up 12% YoY, but check average growth is lagging behind guest count growth. Delivery mix has increased, impacting overall margin.";
     recommendations = `
1. **Immediate**: Analyze delivery menu pricing to ensure margin protection.
2. **Short-term**: Launch a server competition to boost appetizer and dessert sales (check average).
3. **Strategic**: Evaluate loyalty program performance to drive repeat visits.
`;
  } else if (query.toLowerCase().includes('margin') || query.toLowerCase().includes('profit')) {
     category = "Profitability Analysis";
     executiveSummary = "Net margin improved 32.2% driven by operational leverage on higher sales. Flow-through rate is strong at 45%.";
     recommendations = `
1. **Immediate**: Protect recent gains by locking in labor schedules.
2. **Short-term**: Reinvest a portion of excess profit into Q4 marketing.
3. **Strategic**: Evaluate potential for debt paydown or capital improvements.
`;
  }

  return `
# ${category}: ${query.length > 30 ? query.substring(0, 30) + '...' : query}
**Date:** ${today}

## Executive Summary
${executiveSummary}

## Key Findings
- **Variance**: Significant deviation observed in week 3.
- **Trend**: 3-month positive trajectory but recent volatility.
- **Benchmark**: Currently performing in the top 40% of peer group.

## Detailed Breakdown

### Financial Impact
| Category | Current | Previous | Variance |
|----------|---------|----------|----------|
| Revenue  | $133,042| $154,351 | -13.8%   |
| COGS     | $55,670 | $57,494  | -3.2%    |
| Labor    | $16,156 | $18,408  | -12.2%   |

### Operational Context
The shift in numbers correlates with recent operational changes and seasonal traffic patterns. We noticed a direct correlation between specific shifts and the reported variance.

## Recommendations
${recommendations}

_Generated by Munch AI Assistant_
  `;
};

export function generateMockResponse(query: string): MockResponse {
  const q = query.toLowerCase();

  // Specific "Explain Section" Logic
  if (q.includes("explain") && q.includes("section")) {
    if (q.includes("revenue")) {
      return {
        content: `**1. Definition**
The Revenue Analysis section breaks down your top-line sales performance by channel (Dine-in, Delivery, Takeout), day part, and customer segment. It tells you *where* your money is coming from and *how* it's trending.

**2. Key Metrics to Watch**
• **Channel Mix**: Currently 67% Dine-in / 33% Off-premise. A shift >5% indicates a changing business model.
• **Average Check**: $42.50 (Dinner) vs $18.20 (Lunch).
• **Guest Count Trend**: +2.5% YoY. This is the healthiest form of growth (vs price increases).

**3. Actionable Steps**
• **Optimize Delivery Menu**: Since delivery is 21% of sales, ensure high-margin items are featured on DoorDash.
• **Upsell Training**: Dinner check average is flat; run a contest to boost dessert attachment rate.
• **Lunch Traffic**: Volume is soft on Tuesdays; consider a "Local Business Lunch" promo.`,
        showArtifact: false,
        followUpQuestions: [
          { type: "report", label: "View Channel Mix", report_type: "sales_drivers", params: { decomposition: true } },
          { type: "chat", label: "Lunch vs Dinner", intent: "Compare lunch and dinner performance" }
        ]
      };
    }

    if (q.includes("profit") || q.includes("margin")) {
      return {
        content: `**1. Definition**
The Profitability/Margin section reveals how much revenue you keep after paying expenses. It highlights your Net Operating Income (NOI) and key margin ratios (Prime Cost, EBITDA).

**2. Key Metrics to Watch**
• **Net Profit Margin**: Currently 13.3% (Target: 15%).
• **Prime Cost**: 54.2% (COGS + Labor). This is your most controllable metric. Target is <60%.
• **Flow-Through**: 32.2%. This measures how much of every *extra* dollar of sales turns into profit.

**3. Actionable Steps**
• **Reduce Waste**: Food cost is slightly high (31%). Implement a daily waste log.
• **Labor Scheduling**: Cut 10 hours from the Tuesday/Wednesday prep schedule to align with demand.
• **Review Fixed Costs**: Renegotiate the linen contract to save $450/month.`,
        showArtifact: false,
        followUpQuestions: [
          { type: "report", label: "Margin Analysis", report_type: "margin_decomposition", params: { period: "current" } },
          { type: "chat", label: "Prime Cost Trend", intent: "Show me the Prime Cost trend for the last 6 months" }
        ]
      };
    }

    if (q.includes("labor") || q.includes("workforce")) {
      return {
        content: `**1. Definition**
The Labor Analysis section tracks your workforce efficiency and costs. It splits labor into Management (Fixed) and Hourly (Variable) buckets.

**2. Key Metrics to Watch**
• **Labor Cost %**: 33.0% of Sales. (Benchmark: 30-35%).
• **Sales Per Labor Hour (SPLH)**: $48.50. A measure of productivity.
• **Overtime %**: 4.2% of total hours. Ideally should be <2%.

**3. Actionable Steps**
• **Enforce Clock-ins**: Prevent early clock-ins to save ~15 mins per shift per employee.
• **Cross-Train Staff**: Enable dishwashers to help with prep during downtime to boost SPLH.
• **Manager Floor Time**: Ensure managers are cutting staff aggressively when sales slow down post-rush.`,
        showArtifact: false,
        followUpQuestions: [
          { type: "report", label: "Overtime Report", report_type: "overtime_analysis", params: { role_breakdown: true } },
          { type: "chat", label: "Analyze SPLH", intent: "How has Sales Per Labor Hour changed vs last month?" }
        ]
      };
    }
  }

  if (q.includes("health") || q.includes("score")) {
    return {
      content: `**Summary Insight**
Your Financial Health Score is **82/100 (Healthy)**. You are outperforming your peer group by 12 points.

**Key Drivers**
• **Strong Profitability**: Net margin at 16.8% vs 12% target.
• **Labor Efficiency**: Sales per Labor Hour is up $4.50 vs last month.
• **Stability**: Cash reserves have stabilized at 2.1 months of coverage.

**Implications**
You have the financial buffer to invest in growth initiatives or deferred maintenance without risking cash flow.

**Recommended Next Steps**
• Review capital expenditure wishlist for potential Q4 investment.
• Evaluate bonus pool distribution for management team.`,
      showArtifact: false,
      followUpQuestions: [
        { type: "chat", label: "What dragged down stability?", intent: "What dragged down the stability score?" },
        { type: "report", label: "Labor efficiency trend", report_type: "labor_efficiency", params: { metric: "splh" } },
        { type: "chat", label: "Compare to last year", intent: "Compare health score to last year" }
      ]
    };
  }

  if (q.includes("margin") || q.includes("profit")) {
    return {
      content: `**Summary Insight**
Net Operating Income increased by **32.2%** to $23,424 this period.

**Key Drivers**
• **COGS Reduction**: Down 2.1% due to better waste management and menu engineering.
• **Labor Efficiency**: Improved by 3.3% driven by optimized scheduling.
• **Revenue Growth**: Up 3.7% year-over-year, leveraging fixed costs.

**Implications**
Your operational leverage is working—incremental sales are flowing through to the bottom line at a high rate.

**Recommended Next Steps**
• Lock in the new schedule template that drove labor savings.
• Reinvest a portion of profits into marketing to sustain top-line growth.`,
      showArtifact: false,
      followUpQuestions: [
        { type: "report", label: "Break down COGS", report_type: "cogs_breakdown", params: { focus: "savings" } },
        { type: "report", label: "Margin impact analysis", report_type: "margin_decomposition", params: { period: "current" } },
        { type: "chat", label: "Sustainable?", intent: "Is this margin sustainable next month?" }
      ]
    };
  }

  if (q.includes("labor") || q.includes("staff")) {
    return {
      content: `**Summary Insight**
Labor costs are trending positively at **33% of revenue** (Target: 35%).

**Key Drivers**
• **FOH Efficiency**: New zone assignments increased tables per server without impacting service.
• **Overtime Control**: Scheduled overtime down 40% vs prior month.
• **Volume variance**: Higher than expected sales leveraged fixed management salaries.

**Implications**
You are getting more productivity per dollar spent. However, watch for burnout indicators if staffing runs too lean.

**Recommended Next Steps**
• Monitor guest feedback to ensure service levels aren't slipping.
• Reward the team for the efficiency gains with a targeted incentive.`,
      showArtifact: true,
      followUpQuestions: [
        { type: "report", label: "Overtime by role", report_type: "overtime_analysis", params: { role_breakdown: true } },
        { type: "report", label: "Labor efficiency vs LY", report_type: "labor_efficiency", params: { compare: "last_year" } },
        { type: "chat", label: "Hourly rate changes", intent: "Analyze hourly rate changes" }
      ]
    };
  }

  if (q.includes("cost") || q.includes("expense") || q.includes("cogs")) {
    return {
      content: `**Summary Insight**
COGS is tracking at **31.2% of revenue** (Target: 30%).

**Key Drivers**
• **Protein Prices**: Beef prices increased 8% vs prior month due to market conditions.
• **Waste**: Spoilage rate on produce is up 0.5% - worth investigating walk-in temps.
• **Menu Mix**: Higher-cost entrees are selling well, which naturally increases food cost %.

**Implications**
The overage is primarily driven by external factors (market prices) and positive mix shift. Not a structural issue.

**Recommended Next Steps**
• Lock in beef prices with your distributor for the next quarter.
• Perform a spot check on the walk-in cooler thermostat.
• Consider a small price increase on high-cost entrees to protect margin.`,
      showArtifact: false,
      followUpQuestions: [
        { type: "report", label: "Vendor spend analysis", report_type: "vendor_spend", params: { focus: "proteins" } },
        { type: "chat", label: "Waste breakdown", intent: "Show me waste breakdown by category" },
        { type: "chat", label: "Menu pricing impact", intent: "What if we raised prices 3% on top 5 items?" }
      ]
    };
  }

  // Default response
  return {
    content: `**Summary Insight**
I've analyzed that for you. Based on the current period data, performance is **tracking ahead of forecast**.

**Key Drivers**
• **Sales Volume**: Tracking 4.2% above projection.
• **Cost Control**: Prime costs are 1.5% below budget.

**Implications**
You are on track to exceed quarterly profit targets if this trend continues.

**Recommended Next Steps**
• Review inventory levels to ensure you can support the higher volume.
• Check if any deferred maintenance needs attention.`,
    showArtifact: false,
    followUpQuestions: [
      { type: "report", label: "Sales Breakdown", report_type: "sales_drivers", params: {} },
      { type: "report", label: "Labor vs Sales", report_type: "labor_efficiency", params: {} },
      { type: "chat", label: "Top variance items", intent: "Analyze top variance items" }
    ]
  };
}
